services:
  app:
    image: tahili-system-app:2790a7f30b2baa35c8e40bd9acb00ff37e2840b3
    pull_policy: never
    environment:
      TAHILI_ENVIRONMENT: production
      FARO_ENABLED: "true"
      OTEL_ENABLED: "true"
    volumes:
      - production_uploads:/app/uploads

volumes:
  production_uploads:
    external: true
    name: tahili-system_uploads_v3
