"use server";

import { randomBytes } from "crypto";
import { prisma } from "@/lib/db";
import { assertPerm, requireSession } from "@/lib/access";
import { saveFile } from "@/lib/storage";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

async function actor(permission: string) { const session=await requireSession(); await assertPerm(permission); return {id:(session.user as any).id as string,name:session.user?.name||""}; }
const voucherNo=()=>`WE-${new Date().getFullYear()}-${randomBytes(4).toString("hex").toUpperCase()}`;
function refresh(id?:string){revalidatePath("/finance/expenses");revalidatePath("/finance/expenses/reports");revalidatePath("/finance");if(id)revalidatePath(`/finance/expenses/${id}`)}

export async function createExpense(fd:FormData){
  const who=await actor("expenses.create"); const file=fd.get("attachment") as File|null; const saved=file&&file.size>0?await saveFile(file):null;
  const settings=await prisma.orgSetting.findUnique({where:{id:1},select:{expenseApprovalLevels:true}});
  const expense=await prisma.$transaction(async(tx)=>{
    const row=await tx.woundedExpense.create({data:{voucherNo:voucherNo(),patientId:fd.get("patientId")?.toString()||"",beneficiary:fd.get("beneficiary")?.toString().trim()||"",beneficiaryEntity:fd.get("beneficiaryEntity")?.toString()||null,expenseType:fd.get("expenseType")?.toString()||"مساعدة",reason:fd.get("reason")?.toString().trim()||"",amount:fd.get("amount")?.toString()||"0",currency:fd.get("currency")?.toString()||"IQD",dueDate:fd.get("dueDate")?new Date(fd.get("dueDate")!.toString()):null,createdById:who.id,notes:fd.get("notes")?.toString()||null,costCenter:fd.get("costCenter")?.toString()||null,department:fd.get("department")?.toString()||null,paymentMethod:fd.get("paymentMethod")?.toString()||null,financialReference:fd.get("financialReference")?.toString()||null,requiredApprovalLevels:Math.max(1,Math.min(5,settings?.expenseApprovalLevels||1))}});
    if(saved)await tx.woundedExpenseAttachment.create({data:{expenseId:row.id,fileName:saved.name,fileUrl:`/api/files/${saved.key}`}});
    await tx.auditLog.create({data:{userId:who.id,action:"CREATE",tableName:"wounded_expenses",recordId:row.id,newValue:{voucherNo:row.voucherNo,status:"DRAFT",patientId:row.patientId}}});return row;
  });
  redirect(`/finance/expenses/${expense.id}`)
}

export async function updateExpenseDraft(id:string,fd:FormData){const who=await actor("expenses.create");await prisma.$transaction(async(tx)=>{const before=await tx.woundedExpense.findUniqueOrThrow({where:{id}});if(before.status!=="DRAFT")throw new Error("لا يمكن تعديل الصرفية بعد تقديمها");await tx.woundedExpense.update({where:{id},data:{patientId:fd.get("patientId")?.toString()||before.patientId,beneficiary:fd.get("beneficiary")?.toString()||before.beneficiary,expenseType:fd.get("expenseType")?.toString()||before.expenseType,reason:fd.get("reason")?.toString()||before.reason,amount:fd.get("amount")?.toString()||before.amount,paymentMethod:fd.get("paymentMethod")?.toString()||null,notes:fd.get("notes")?.toString()||null}});await tx.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expenses",recordId:id,newValue:{draftUpdated:true}}})});refresh(id)}

export async function submitExpense(id:string){const who=await actor("expenses.submit");await prisma.$transaction(async(tx)=>{const row=await tx.woundedExpense.findUniqueOrThrow({where:{id}});if(row.status!=="DRAFT")throw new Error("المسودة غير متاحة للتقديم");await tx.woundedExpense.update({where:{id},data:{status:"SUBMITTED"}});await tx.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expenses",recordId:id,oldValue:{status:"DRAFT"},newValue:{status:"SUBMITTED"}}});await tx.notification.create({data:{targetRole:"MANAGER",title:"صرفية تنتظر الاعتماد",body:"يوجد طلب صرف يحتاج مراجعة.",link:`/finance/expenses/${id}`}})});refresh(id)}

export async function decideExpense(id:string,decision:"APPROVED"|"REJECTED",fd:FormData){const who=await actor("expenses.approve");await prisma.$transaction(async(tx)=>{const row=await tx.woundedExpense.findUniqueOrThrow({where:{id},include:{approvals:true}});if(row.status!=="SUBMITTED")throw new Error("الصرفية ليست بانتظار الاعتماد");if(row.createdById===who.id)throw new Error("لا يجوز لمنشئ الصرفية اعتماد طلبه");const level=row.approvals.length+1;const reason=fd.get("reason")?.toString().trim()||null;if(decision==="REJECTED"&&!reason)throw new Error("سبب الرفض مطلوب");await tx.woundedExpenseApproval.create({data:{expenseId:id,level,decision,userId:who.id,reason}});const complete=decision==="APPROVED"&&level>=row.requiredApprovalLevels;const status=decision==="REJECTED"?"REJECTED":complete?"APPROVED":"SUBMITTED";await tx.woundedExpense.update({where:{id},data:{status}});await tx.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expense_approvals",recordId:id,newValue:{level,decision,status}}});await tx.notification.create({data:{targetUserId:row.createdById,title:decision==="REJECTED"?"رُفض طلب الصرف":"قُبل اعتماد صرفية",body:complete?"اكتملت مستويات الاعتماد.":decision==="REJECTED"?"راجع سبب القرار في التفاصيل.":"سُجل مستوى اعتماد وبقيت متابعة.",link:`/finance/expenses/${id}`}})});refresh(id)}

export async function markExpenseReady(id:string){const who=await actor("expenses.approve");await prisma.$transaction(async(tx)=>{const row=await tx.woundedExpense.findUniqueOrThrow({where:{id}});if(row.status!=="APPROVED")throw new Error("يجب اكتمال الاعتماد أولاً");await tx.woundedExpense.update({where:{id},data:{status:"READY_FOR_PAYMENT"}});await tx.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expenses",recordId:id,oldValue:{status:row.status},newValue:{status:"READY_FOR_PAYMENT"}}});await tx.notification.create({data:{targetRole:"ACCOUNTANT",title:"صرفية جاهزة للتنفيذ",body:"يوجد سند معتمد جاهز للصرف.",link:`/finance/expenses/${id}`}})});refresh(id)}

export async function payExpense(id:string,fd:FormData){const who=await actor("expenses.pay");const key=fd.get("idempotencyKey")?.toString()||"";if(!key)throw new Error("مفتاح التنفيذ مفقود");await prisma.$transaction(async(tx)=>{const row=await tx.woundedExpense.findUniqueOrThrow({where:{id}});if(row.status==="PAID")return;if(row.status!=="READY_FOR_PAYMENT")throw new Error("الصرفية غير جاهزة للصرف");const duplicate=await tx.woundedExpense.findFirst({where:{payoutIdempotencyKey:key,id:{not:id}}});if(duplicate)throw new Error("عملية الصرف مسجلة مسبقاً");await tx.woundedExpense.update({where:{id},data:{status:"PAID",paidAt:new Date(),paidById:who.id,payoutIdempotencyKey:key,paymentMethod:fd.get("paymentMethod")?.toString()||row.paymentMethod,financialReference:fd.get("financialReference")?.toString()||row.financialReference}});await tx.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expenses",recordId:id,oldValue:{status:row.status},newValue:{status:"PAID",paid:true}}});await tx.notification.create({data:{targetUserId:row.createdById,title:"اكتمل تنفيذ الصرفية",body:"اكتملت عملية الصرف ويمكن طباعة السند.",link:`/finance/expenses/${id}`}})},{isolationLevel:"Serializable"});refresh(id)}

export async function cancelExpense(id:string,fd:FormData){const who=await actor("expenses.correct");const reason=fd.get("reason")?.toString().trim();if(!reason)throw new Error("سبب الإلغاء مطلوب");await prisma.$transaction(async(tx)=>{const row=await tx.woundedExpense.findUniqueOrThrow({where:{id}});if(row.status==="PAID")throw new Error("استخدم العكس المالي للصرفية المصروفة");if(row.status==="CANCELLED")return;await tx.woundedExpense.update({where:{id},data:{status:"CANCELLED",correctionReason:reason}});await tx.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expenses",recordId:id,oldValue:{status:row.status},newValue:{status:"CANCELLED",reason}}})});refresh(id)}

export async function createExpenseCorrection(id:string,fd:FormData){const who=await actor("expenses.correct");const reason=fd.get("reason")?.toString().trim();const type=fd.get("correctionType")?.toString() as "CORRECTION"|"REVERSAL";if(!reason)throw new Error("سبب التصحيح مطلوب");const correction=await prisma.$transaction(async(tx)=>{const original=await tx.woundedExpense.findUniqueOrThrow({where:{id}});const amount=type==="REVERSAL"?original.amount.negated():fd.get("amount")?.toString()||"0";const row=await tx.woundedExpense.create({data:{voucherNo:voucherNo(),patientId:original.patientId,beneficiary:original.beneficiary,beneficiaryEntity:original.beneficiaryEntity,expenseType:original.expenseType,reason:`${type==="REVERSAL"?"عكس":"تصحيح"}: ${original.reason}`,amount,currency:original.currency,createdById:who.id,costCenter:original.costCenter,department:original.department,paymentMethod:original.paymentMethod,financialReference:original.financialReference,parentExpenseId:id,correctionType:type,correctionReason:reason,requiredApprovalLevels:original.requiredApprovalLevels}});await tx.auditLog.create({data:{userId:who.id,action:"CREATE",tableName:"wounded_expenses",recordId:row.id,newValue:{parentExpenseId:id,correctionType:type,reason}}});return row;});redirect(`/finance/expenses/${correction.id}`)}

export async function recordExpensePrint(id:string){const who=await actor("expenses.print");await prisma.auditLog.create({data:{userId:who.id,action:"UPDATE",tableName:"wounded_expenses",recordId:id,newValue:{printed:true}}})}
