import Link from "next/link";
import { createCenterProgram, saveCenterMembership } from "@/app/(app)/centers/actions";
import { SERVICE_LABELS } from "@/lib/center-workspaces";
import { fmtDate } from "@/lib/labels";

export function CenterWorkspace({ slug, center, services, referrals, programs, members, users, canManageMembers, canManagePrograms, canViewSensitive }: any) {
  return <div className="space-y-5"><div className="flex flex-wrap gap-2"><Link href={`/centers/${slug}/today`} className="btn-primary">جلسات اليوم</Link><Link href={`/centers/${slug}/resources`} className="btn-ghost">الموارد والحجوزات</Link></div>
    <div className="grid gap-3 md:grid-cols-4"><Metric label="إحالات تنتظر القبول" value={referrals.length} /><Metric label="برامج نشطة" value={programs.filter((p:any)=>p.status === "ACTIVE").length} /><Metric label="أعضاء المركز" value={members.length} /><Metric label="جلسات قادمة" value={programs.reduce((sum:number,p:any)=>sum+p.sessions.length,0)} /></div>
    {canManagePrograms ? <form action={createCenterProgram.bind(null, center.id)} className="card grid gap-3 p-5 md:grid-cols-2" autoComplete="off"><h2 className="text-lg font-bold md:col-span-2">قبول الإحالة وإنشاء البرنامج</h2><label className="label">الإحالة<select name="referralRequestId" className="input mt-1" required><option value="">اختر الإحالة</option>{referrals.map((r:any)=><option key={r.id} value={r.id}>{r.patient.fullName}، {r.requestedService}</option>)}</select></label><label className="label">الخدمة<select name="serviceType" className="input mt-1" required>{services.map((service:string)=><option key={service} value={service}>{SERVICE_LABELS[service]}</option>)}</select></label><label className="label">نوع المسار<input name="track" className="input mt-1" placeholder="مثال: تأهيل بالفن…" /></label><label className="label">نمط الجلسة<select name="mode" className="input mt-1"><option value="INDIVIDUAL">فردية</option><option value="GROUP">جماعية</option></select></label><label className="label">المسؤول<select name="assignedToId" className="input mt-1"><option value="">غير مسند</option>{members.filter((m:any)=>["THERAPIST","DEVICE_OPERATOR","HEAD_THERAPIST"].includes(m.role)).map((m:any)=><option key={m.id} value={m.userId}>{m.user.fullName}، {m.specialty || m.role}</option>)}</select></label><label className="label">عدد الجلسات<input name="plannedSessions" type="number" min="1" max="100" className="input mt-1" /></label><label className="label">تاريخ البداية<input name="startDate" type="date" className="input mt-1" /></label><label className="label">النهاية المتوقعة<input name="expectedEndDate" type="date" className="input mt-1" /></label><label className="label md:col-span-2">التقييم الأولي<textarea name="initialSummary" className="input mt-1" rows={3} required /></label><label className="label">القدرات الوظيفية<textarea name="functionalCapacity" className="input mt-1" rows={2} /></label><label className="label">الأهداف<textarea name="goals" className="input mt-1" rows={2} /></label><label className="label md:col-span-2">الخطة أو البروتوكول<textarea name="protocol" className="input mt-1" rows={3} /></label>{canViewSensitive && services.includes("PSYCHOLOGICAL") ? <label className="label md:col-span-2">ملاحظات نفسية حساسة<textarea name="sensitiveNotes" className="input mt-1" rows={2} /></label> : null}<div className="md:col-span-2"><button className="btn-primary">قبول وإنشاء البرنامج</button></div></form> : null}
    <section className="card overflow-hidden"><h2 className="border-b p-4 font-bold">برامج المركز</h2><table className="w-full text-sm"><thead><tr><th className="th">المراجع</th><th className="th">الخدمة</th><th className="th">المسؤول</th><th className="th">الحالة</th><th className="th">إجراء</th></tr></thead><tbody>{programs.map((p:any)=><tr key={p.id}><td className="td"><Link href={`/patients/${p.patientId}`} className="text-brand-700 hover:underline">{p.patient.fullName}</Link></td><td className="td">{SERVICE_LABELS[p.serviceType]}</td><td className="td">{p.assignedTo?.fullName || "غير مسند"}</td><td className="td">{p.status === "COMPLETED" ? "مكتمل" : p.status === "ACTIVE" ? "نشط" : "تقييم"}</td><td className="td"><Link href={`/centers/${slug}/programs/${p.id}`} className="text-brand-700 hover:underline">فتح البرنامج</Link></td></tr>)}</tbody></table></section>
    {canManageMembers ? <form action={saveCenterMembership.bind(null, center.id)} className="card grid gap-3 p-5 md:grid-cols-3" autoComplete="off"><h2 className="font-bold md:col-span-3">إدارة عضوية المركز</h2><label className="label">المستخدم<select name="userId" className="input mt-1" required>{users.map((u:any)=><option key={u.id} value={u.id}>{u.fullName}</option>)}</select></label><label className="label">الصفة<select name="role" className="input mt-1"><option value="CENTER_MANAGEMENT">إدارة مركز</option><option value="HEAD_THERAPIST">رئيس معالجين</option><option value="THERAPIST">معالج</option><option value="DEVICE_OPERATOR">مشغّل جهاز</option></select></label><label className="label">الاختصاص<input name="specialty" className="input mt-1" /></label><label className="label">تاريخ البداية<input name="startDate" type="date" className="input mt-1" /></label><label className="label">تاريخ النهاية<input name="endDate" type="date" className="input mt-1" /></label><div className="self-end"><button className="btn-primary">حفظ العضوية</button></div></form> : null}
    <section className="card p-5"><h2 className="font-bold">عضويات المركز</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{members.map((m:any)=><div key={m.id} className="rounded-lg border p-3"><div className="font-medium">{m.user.fullName}</div><div className="text-sm text-gray-600">{m.specialty || m.role}</div><div className="text-xs text-gray-500">من {fmtDate(m.startDate)}، {m.status}</div></div>)}</div></section>
  </div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="card p-4"><div className="text-2xl font-bold text-brand-700">{value}</div><div className="text-sm text-gray-600">{label}</div></div>; }
