apiVersion: 1

datasources:
  - name: Tempo
    uid: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: Loki
        tags:
          - key: service.name
            value: service
          - key: deployment.environment
            value: environment
        filterByTraceID: false
        filterBySpanID: false
