import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { currentPerms, getSession, requirePerm } from "@/lib/access";
import { PageHeader } from "@/components/PageHeader";
import { ReferralStatus, REFERRAL_STATUS_LABELS } from "@/components/referrals/ReferralStatus";
import { fmtDateTime } from "@/lib/labels";
import { transitionReferralAction, updateReferralAction } from "../actions";

export const dynamic = "force-dynamic";

export default async function ReferralDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ msg?: string }> }) {
  await requirePerm("referrals.view");
  const { id } = await params;
  const sp = await searchParams;
  const [request, perms, session, doctors, centers, logs] = await Promise.all([
    prisma.referralRequest.findUnique({ where: { id }, include: { patient: { select: { id: true, fullName: true, fileNumber: true } }, createdBy: { select: { fullName: true } }, assignedReviewer: { select: { fullName: true } }, destinationCenter: { select: { name: true } }, officialDocument: true, careStage: true, reviewedBy: { select: { fullName: true } }, acceptedBy: { select: { fullName: true } } } }),
    currentPerms(), getSession(),
    prisma.user.findMany({ where: { isActive: true, role: "DOCTOR" }, select: { id: true, fullName: true }, orderBy: { fullName: "asc" } }),
    prisma.center.findMany({ orderBy: { name: "asc" } }),
    prisma.auditLog.findMany({ where: { tableName: "referral_requests", recordId: id }, include: { user: { select: { fullName: true } } }, orderBy: { createdAt: "desc" } }),
  ]);
  if (!request) notFound();
  const uid = (session?.user as any)?.id;
  const role = (session?.user as any)?.role;
  const canPrepare = request.status === "DRAFT" && perms.has("referrals.updateStatus") && (role === "RESIDENT" || role === "DOCTOR");
  const canPrint = request.status === "PENDING_PRINT" && perms.has("referrals.print");
  const canSend = request.status === "READY" && request.destinationScope === "EXTERNAL" && perms.has("referrals.updateStatus") && ["MANAGER","DATA_ENTRY","ADMIN"].includes(role);
  const canAccept = request.status === "READY" && request.destinationScope !== "EXTERNAL" && perms.has("referrals.accept");
  const canResult = request.status === "SENT" && perms.has("referrals.recordResult");
  const canReview = request.status === "RESULT_RECEIVED" && perms.has("referrals.reviewResult") && role === "DOCTOR" && request.assignedReviewerId === uid;
  const canCancel = ["DRAFT","PENDING_PRINT","READY","SENT"].includes(request.status) && perms.has("referrals.cancel");
  return <div className="space-y-5">
    <PageHeader title="تفاصيل طلب الفحص أو الإحالة" subtitle={`${request.patient.fullName}، ملف #${request.patient.fileNumber}`} icon="↗" />
    {sp.msg ? <div aria-live="polite" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{sp.msg}</div> : null}
    <div className="flex flex-wrap items-center justify-between gap-2"><Link href="/referrals" className="btn-ghost">العودة إلى الطلبات</Link><div className="flex gap-2"><ReferralStatus status={request.status} /><Link href={`/patients/${request.patient.id}`} className="btn-ghost">ملف المراجع</Link>{request.officialDocument ? <Link href={`/referrals/${id}/official`} className="btn-ghost">كتاب الإرسال</Link> : null}</div></div>
    <section className="card grid gap-4 p-5 md:grid-cols-2" aria-labelledby="medical-request-title"><h2 id="medical-request-title" className="md:col-span-2 text-lg font-bold">القرار الطبي</h2><Info label="النوع" value={request.type} /><Info label="النطاق" value={request.destinationScope} /><Info label="الخدمة المطلوبة" value={request.requestedService} /><Info label="الوجهة" value={request.externalEntity || request.destinationCenter?.name || request.assignedReviewer?.fullName || "غير محددة"} /><div className="md:col-span-2"><Info label="السبب السريري" value={request.clinicalReason} /></div><Info label="المنشئ" value={request.createdBy.fullName} /><Info label="الطبيب المراجع" value={request.assignedReviewer?.fullName || "غير محدد"} /></section>
    {request.status === "DRAFT" ? <form action={updateReferralAction.bind(null, id, request.patientId)} className="card grid gap-3 p-5 md:grid-cols-2" autoComplete="off"><h2 className="md:col-span-2 font-bold">تعديل المسودة</h2><label className="label">النطاق<select name="destinationScope" className="input mt-1" defaultValue={request.destinationScope}><option value="EXTERNAL">خارجي</option><option value="INTERNAL_SPECIALIST">اختصاص داخلي</option><option value="INTERNAL_CENTER">مركز داخلي</option></select></label><label className="label">النوع<select name="type" className="input mt-1" defaultValue={request.type}>{["LAB","RADIOLOGY","IMAGING","SPECIALIST","TREATMENT_CENTER","HOSPITAL","OTHER"].map((v) => <option key={v}>{v}</option>)}</select></label><label className="label">الجهة الخارجية<input name="externalEntity" className="input mt-1" defaultValue={request.externalEntity || ""} /></label><label className="label">المركز الداخلي<select name="destinationCenterId" className="input mt-1" defaultValue={request.destinationCenterId || ""}><option value="">غير محدد</option>{centers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="label">الطبيب المراجع<select name="assignedReviewerId" className="input mt-1" defaultValue={request.assignedReviewerId || ""}><option value="">غير محدد</option>{doctors.map((d) => <option key={d.id} value={d.id}>{d.fullName}</option>)}</select></label><input type="hidden" name="residentReviewId" value={request.residentReviewId || ""} /><label className="label">الخدمة<input name="requestedService" className="input mt-1" defaultValue={request.requestedService} required /></label><label className="label md:col-span-2">السبب السريري<textarea name="clinicalReason" className="input mt-1" rows={3} defaultValue={request.clinicalReason} required /></label><div className="md:col-span-2"><button className="btn-primary">حفظ المسودة</button></div></form> : null}
    <section className="card space-y-3 p-5"><h2 className="font-bold">الإجراءات المتاحة</h2>{canPrepare ? <form action={transitionReferralAction.bind(null, id, request.destinationScope === "EXTERNAL" ? "PENDING_PRINT" : "READY")}><button className="btn-primary">{request.destinationScope === "EXTERNAL" ? "إرسال إلى قائمة الطباعة" : "تجهيز الإحالة الداخلية"}</button></form> : null}{canPrint ? <form action={transitionReferralAction.bind(null, id, "READY")} className="grid gap-3 md:grid-cols-2"><label className="label">رقم الكتاب<input name="number" className="input mt-1" required /></label><label className="label">تاريخ الكتاب<input name="docDate" type="date" className="input mt-1" required /></label><label className="label md:col-span-2">الموضوع<input name="subject" className="input mt-1" defaultValue={`إرسال المراجع ${request.patient.fullName}`} required /></label><label className="label md:col-span-2">نص الكتاب<textarea name="body" className="input mt-1" rows={3} /></label><div className="md:col-span-2"><button className="btn-primary">إنشاء الكتاب وتأكيد الجاهزية</button></div></form> : null}{canSend ? <form action={transitionReferralAction.bind(null, id, "SENT")}><button className="btn-primary">تأكيد إرسال الطلب</button></form> : null}{canAccept ? <form action={transitionReferralAction.bind(null, id, "ACCEPTED")}><button className="btn-primary">قبول الإحالة الداخلية</button></form> : null}{canResult ? <form action={transitionReferralAction.bind(null, id, "RESULT_RECEIVED")} className="grid gap-3 md:grid-cols-2" encType="multipart/form-data"><label className="label md:col-span-2">ملخص النتيجة<textarea name="resultSummary" className="input mt-1" rows={4} required /></label><label className="label">ملف النتيجة<input name="resultAttachment" type="file" className="input mt-1" accept=".pdf,image/*" /></label><div className="md:col-span-2"><button className="btn-primary">تسجيل وصول النتيجة</button></div></form> : null}{canReview ? <form action={transitionReferralAction.bind(null, id, "REVIEWED")}><button className="btn-primary">اعتماد مراجعة النتيجة</button></form> : null}{canCancel ? <form action={transitionReferralAction.bind(null, id, "CANCELLED")} className="flex flex-wrap items-end gap-2"><label className="label flex-1">سبب الإلغاء<input name="cancellationReason" className="input mt-1" required /></label><button className="btn-danger">إلغاء الطلب</button></form> : null}{![canPrepare,canPrint,canSend,canAccept,canResult,canReview,canCancel].some(Boolean) ? <p className="text-sm text-gray-500">لا توجد إجراءات متاحة في الحالة الحالية.</p> : null}</section>
    {request.resultSummary ? <section className="card space-y-3 p-5"><h2 className="font-bold">النتيجة</h2><p className="whitespace-pre-wrap break-words text-sm text-gray-700">{request.resultSummary}</p>{request.resultAttachmentUrl ? <a href={request.resultAttachmentUrl} target="_blank" rel="noreferrer" className="btn-ghost inline-flex">فتح مرفق النتيجة</a> : null}<div className="text-xs text-gray-500">راجعها: {request.reviewedBy?.fullName || "بانتظار المراجعة"}</div></section> : null}
    <section className="card p-5"><h2 className="font-bold">سجل انتقالات الطلب</h2><ol className="mt-3 space-y-3">{logs.map((log) => <li key={log.id} className="border-r-2 border-brand-200 pr-3 text-sm"><div className="font-medium">{(log.newValue as any)?.status ? REFERRAL_STATUS_LABELS[(log.newValue as any).status as keyof typeof REFERRAL_STATUS_LABELS] : "إنشاء الطلب"}</div><div className="text-xs text-gray-500">{log.user?.fullName || "النظام"}، {fmtDateTime(log.createdAt)}</div></li>)}</ol></section>
  </div>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-gray-50 p-3"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 break-words font-medium text-gray-800">{value}</div></div>; }
