import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { currentPerms } from "@/lib/access";
import { getOrg } from "@/lib/org";
import { fmtDate } from "@/lib/labels";
import { amountInArabic } from "@/lib/arabic-money";
import { ExpensePrintButton } from "@/components/expenses/ExpensePrintButton";

export const dynamic="force-dynamic";
export default async function ExpenseVoucher({params}:{params:Promise<{id:string}>}){const perms=await currentPerms();if(!perms.has("expenses.print")||!perms.has("expenses.amounts"))redirect("/");const {id}=await params;const [row,org]=await Promise.all([prisma.woundedExpense.findUnique({where:{id},include:{patient:true,createdBy:true,paidBy:true,approvals:{include:{user:true},orderBy:{level:"asc"}}}}),getOrg()]);if(!row)notFound();return <main className="mx-auto max-w-3xl space-y-4"><div className="flex justify-between print:hidden"><Link href={`/finance/expenses/${id}`} className="btn-ghost">العودة للتفاصيل</Link><ExpensePrintButton id={id}/></div><article className="card min-h-[900px] p-10"><header className="border-b-2 border-brand-700 pb-5 text-center"><h1 className="text-2xl font-bold text-brand-800">{org.name}</h1><p className="mt-2 text-lg font-semibold">سند صرف رسمي</p></header><div className="mt-6 flex justify-between text-sm"><div>التسلسل: <b>{row.voucherNo}</b></div><div>التاريخ: {fmtDate(row.paidAt||row.requestDate)}</div></div><dl className="mt-8 grid grid-cols-2 gap-x-8 gap-y-5"><Field label="المراجع" value={`${row.patient.fullName}، ملف #${row.patient.fileNumber}`}/><Field label="المستفيد" value={row.beneficiary}/><Field label="الجهة" value={row.beneficiaryEntity||"—"}/><Field label="نوع الصرفية" value={row.expenseType}/><Field label="المبلغ رقماً" value={`${new Intl.NumberFormat("ar-IQ").format(Number(row.amount))} ${row.currency}`}/><Field label="المبلغ كتابةً" value={amountInArabic(Number(row.amount),row.currency)}/><Field label="طريقة الصرف" value={row.paymentMethod||"—"}/><Field label="المرجع المالي" value={row.financialReference||"—"}/><div className="col-span-2"><Field label="سبب الصرف" value={row.reason}/></div></dl><div className="mt-10 grid grid-cols-3 gap-8 text-center text-sm"><div className="border-t pt-2">منشئ الطلب<br/>{row.createdBy.fullName}</div><div className="border-t pt-2">الاعتماد<br/>{row.approvals.map((a)=>a.user.fullName).join("، ")||"—"}</div><div className="border-t pt-2">منفذ الصرف<br/>{row.paidBy?.fullName||"—"}</div></div></article></main>}
function Field({label,value}:{label:string;value:string}){return <div className="border-b pb-2"><dt className="text-sm text-gray-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
